name: RNAseq_nf
channels:
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - trinity=2.8.4
    - fastqc=0.11.8
    - multiqc=1.6
    - atropos=1.1.18
    - r=3.5.1
    - bioconductor-deseq2=1.8.2
    - bioconductor-tximport=1.8.0
