name: RNAseq_nf
channels:
    - bioconda
    - conda-forge
    - defaults
dependencies:
    - fastqc=0.11.8
    - multiqc=1.6
    - fastp=0.19.5
    - salmon=0.11.3
    - font-ttf-dejavu-sans-mono=2.37 #for fastqc
